config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :roomtables
  resources :outpatients
  resources :labtables
  resources :inpatients
  resources :doctortables
  resources :bills
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/inpatient.rb
class Inpatient < ApplicationRecord
    belongs_to :roomtable
    belongs_to :labtable
    
end

app/controllers/inpatients_controller.rb
class InpatientsController < ApplicationController
  before_action :set_inpatient, only: [:show, :edit, :update, :destroy]

  # GET /inpatients
  # GET /inpatients.json
  def index
    @inpatients = Inpatient.all
  end

  # GET /inpatients/1
  # GET /inpatients/1.json
  def show
  end

  # GET /inpatients/new
  def new
    @inpatient = Inpatient.new
  end

  # GET /inpatients/1/edit
  def edit
  end

  # POST /inpatients
  # POST /inpatients.json
  def create
    @inpatient = Inpatient.new(inpatient_params)

    respond_to do |format|
      if @inpatient.save
        format.html { redirect_to @inpatient, notice: 'Inpatient was successfully created.' }
        format.json { render :show, status: :created, location: @inpatient }
      else
        format.html { render :new }
        format.json { render json: @inpatient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inpatients/1
  # PATCH/PUT /inpatients/1.json
  def update
    respond_to do |format|
      if @inpatient.update(inpatient_params)
        format.html { redirect_to @inpatient, notice: 'Inpatient was successfully updated.' }
        format.json { render :show, status: :ok, location: @inpatient }
      else
        format.html { render :edit }
        format.json { render json: @inpatient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inpatients/1
  # DELETE /inpatients/1.json
  def destroy
    @inpatient.destroy
    respond_to do |format|
      format.html { redirect_to inpatients_url, notice: 'Inpatient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inpatient
      @inpatient = Inpatient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inpatient_params
      params.require(:inpatient).permit(:roomtable_id, :labtable_id ,:date_of_add, :date_of_dis, :advance)
    end
end

app/helpers/inpatients_helper.rb
module InpatientsHelper
end

app/views/inpatients/_form.html.erb
<%= simple_form_for(@inpatient) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.collection_select :roomtable_id, Roomtable.order(:room_no), :id, :room_no, prompt: "Choose a Room" %>
    <%= f.collection_select :labtable_id, Labtable.order(:dt), :id, :dt, prompt: "Choose a Lab date" %>

    <%= f.input :date_of_add %>
    <%= f.input :date_of_dis %>
    <%= f.input :advance %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/inpatients/edit.html.erb
<h1>Editing Inpatient</h1>

<%= render 'form', inpatient: @inpatient %>

<%= link_to 'Show', @inpatient %> |
<%= link_to 'Back', inpatients_path %>

app/views/inpatients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inpatients</h1>

<table>
  <thead>
    <tr>
      <th>Date of add</th>
      <th>Date of dis</th>
      <th>Advance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inpatients.each do |inpatient| %>
      <tr>
        <td><%= inpatient.date_of_add %></td>
        <td><%= inpatient.date_of_dis %></td>
        <td><%= inpatient.advance %></td>
        <td><%= link_to 'Show', inpatient %></td>
        <td><%= link_to 'Edit', edit_inpatient_path(inpatient) %></td>
        <td><%= link_to 'Destroy', inpatient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inpatient', new_inpatient_path %>

app/views/inpatients/new.html.erb
<h1>New Inpatient</h1>

<%= render 'form', inpatient: @inpatient %>

<%= link_to 'Back', inpatients_path %>

app/views/inpatients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of add:</strong>
  <%= @inpatient.date_of_add %>
</p>

<p>
  <strong>Date of dis:</strong>
  <%= @inpatient.date_of_dis %>
</p>

<p>
  <strong>Advance:</strong>
  <%= @inpatient.advance %>
</p>

<%= link_to 'Edit', edit_inpatient_path(@inpatient) %> |
<%= link_to 'Back', inpatients_path %>