config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :roomtables
  resources :outpatients
  resources :labtables
  resources :inpatients
  resources :doctortables
  resources :bills
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/labtables_controller.rb
class LabtablesController < ApplicationController
  before_action :set_labtable, only: [:show, :edit, :update, :destroy]

  # GET /labtables
  # GET /labtables.json
  def index
    @labtables = Labtable.all
  end

  # GET /labtables/1
  # GET /labtables/1.json
  def show
  end

  # GET /labtables/new
  def new
    @labtable = Labtable.new
  end

  # GET /labtables/1/edit
  def edit
  end

  # POST /labtables
  # POST /labtables.json
  def create
    @labtable = Labtable.new(labtable_params)

    respond_to do |format|
      if @labtable.save
        format.html { redirect_to @labtable, notice: 'Labtable was successfully created.' }
        format.json { render :show, status: :created, location: @labtable }
      else
        format.html { render :new }
        format.json { render json: @labtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labtables/1
  # PATCH/PUT /labtables/1.json
  def update
    respond_to do |format|
      if @labtable.update(labtable_params)
        format.html { redirect_to @labtable, notice: 'Labtable was successfully updated.' }
        format.json { render :show, status: :ok, location: @labtable }
      else
        format.html { render :edit }
        format.json { render json: @labtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labtables/1
  # DELETE /labtables/1.json
  def destroy
    @labtable.destroy
    respond_to do |format|
      format.html { redirect_to labtables_url, notice: 'Labtable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_labtable
      @labtable = Labtable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def labtable_params
      params.require(:labtable).permit(:doctortable_id,:pid, :dt, :category, :amount)
    end
end

app/helpers/labtables_helper.rb
module LabtablesHelper
end

app/views/labtables/_form.html.erb
<%= simple_form_for(@labtable) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.collection_select :doctortable_id, Doctortable.order(:doctor_name), :id, :doctor_name, prompt: "Choose a Doctor name" %>

    <%= f.input :pid %>
    <%= f.input :dt %>
    <%= f.input :category %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/labtables/edit.html.erb
<h1>Editing Labtable</h1>

<%= render 'form', labtable: @labtable %>

<%= link_to 'Show', @labtable %> |
<%= link_to 'Back', labtables_path %>

app/views/labtables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labtables</h1>

<table>
  <thead>
    <tr>
      <th>Pid</th>
      <th>Dt</th>
      <th>Category</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labtables.each do |labtable| %>
      <tr>
        <td><%= labtable.pid %></td>
        <td><%= labtable.dt %></td>
        <td><%= labtable.category %></td>
        <td><%= labtable.amount %></td>
        <td><%= link_to 'Show', labtable %></td>
        <td><%= link_to 'Edit', edit_labtable_path(labtable) %></td>
        <td><%= link_to 'Destroy', labtable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Labtable', new_labtable_path %>

app/views/labtables/new.html.erb
<h1>New Labtable</h1>

<%= render 'form', labtable: @labtable %>

<%= link_to 'Back', labtables_path %>

app/views/labtables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pid:</strong>
  <%= @labtable.pid %>
</p>

<p>
  <strong>Dt:</strong>
  <%= @labtable.dt %>
</p>

<p>
  <strong>Category:</strong>
  <%= @labtable.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @labtable.amount %>
</p>

<%= link_to 'Edit', edit_labtable_path(@labtable) %> |
<%= link_to 'Back', labtables_path %>