config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :roomtables
  resources :outpatients
  resources :labtables
  resources :inpatients
  resources :doctortables
  resources :bills
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/roomtables_controller.rb
class RoomtablesController < ApplicationController
  before_action :set_roomtable, only: [:show, :edit, :update, :destroy]

  # GET /roomtables
  # GET /roomtables.json
  def index
    @roomtables = Roomtable.all
  end

  # GET /roomtables/1
  # GET /roomtables/1.json
  def show
  end

  # GET /roomtables/new
  def new
    @roomtable = Roomtable.new
  end

  # GET /roomtables/1/edit
  def edit
  end

  # POST /roomtables
  # POST /roomtables.json
  def create
    @roomtable = Roomtable.new(roomtable_params)

    respond_to do |format|
      if @roomtable.save
        format.html { redirect_to @roomtable, notice: 'Roomtable was successfully created.' }
        format.json { render :show, status: :created, location: @roomtable }
      else
        format.html { render :new }
        format.json { render json: @roomtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomtables/1
  # PATCH/PUT /roomtables/1.json
  def update
    respond_to do |format|
      if @roomtable.update(roomtable_params)
        format.html { redirect_to @roomtable, notice: 'Roomtable was successfully updated.' }
        format.json { render :show, status: :ok, location: @roomtable }
      else
        format.html { render :edit }
        format.json { render json: @roomtable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomtables/1
  # DELETE /roomtables/1.json
  def destroy
    @roomtable.destroy
    respond_to do |format|
      format.html { redirect_to roomtables_url, notice: 'Roomtable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomtable
      @roomtable = Roomtable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomtable_params
      params.require(:roomtable).permit(:inpatient_id,:room_no, :room_type, :status)
    end
end

app/helpers/roomtables_helper.rb
module RoomtablesHelper
end

app/views/roomtables/_form.html.erb
<%= simple_form_for(@roomtable) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.collection_select :inpatient_id, Inpatient.order(:date_of_add), :id, :date_of_add, prompt: "Choose a Inpatient date" %>

    <%= f.input :room_no %>
    <%= f.input :room_type %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/roomtables/edit.html.erb
<h1>Editing Roomtable</h1>

<%= render 'form', roomtable: @roomtable %>

<%= link_to 'Show', @roomtable %> |
<%= link_to 'Back', roomtables_path %>

app/views/roomtables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roomtables</h1>

<table>
  <thead>
    <tr>
      <th>Room no</th>
      <th>Room type</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roomtables.each do |roomtable| %>
      <tr>
        <td><%= roomtable.room_no %></td>
        <td><%= roomtable.room_type %></td>
        <td><%= roomtable.status %></td>
        <td><%= link_to 'Show', roomtable %></td>
        <td><%= link_to 'Edit', edit_roomtable_path(roomtable) %></td>
        <td><%= link_to 'Destroy', roomtable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roomtable', new_roomtable_path %>

app/views/roomtables/new.html.erb
<h1>New Roomtable</h1>

<%= render 'form', roomtable: @roomtable %>

<%= link_to 'Back', roomtables_path %>

app/views/roomtables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room no:</strong>
  <%= @roomtable.room_no %>
</p>

<p>
  <strong>Room type:</strong>
  <%= @roomtable.room_type %>
</p>

<p>
  <strong>Status:</strong>
  <%= @roomtable.status %>
</p>

<%= link_to 'Edit', edit_roomtable_path(@roomtable) %> |
<%= link_to 'Back', roomtables_path %>